### ISSUE TITLE
Finalize content of README.md and README.txt files

### ISSUE THREAD

**Issue by bricollins** [reachlocal/reachedge-wordpress-4x-tracking-plugin#11]
Story: https://github.com/reachlocal/reach-edge/issues/22

- [x] [README.md] (https://github.com/reachlocal/capture-wordpress-plugin-4x/blob/master/README.md)
- [x] [README.txt*] (https://github.com/reachlocal/capture-wordpress-plugin-4x/blob/master/reachlocal-tracking/src/README.txt)
- [x] [Wordpress plugins request form**] (https://wordpress.org/plugins/add/)
- [x] Plugin settings text***

====

\* [readme.txt template] (https://wordpress.org/plugins/about/readme.txt)

** request form
![](https://cloud.githubusercontent.com/assets/3331444/6580430/c0b66a86-c70d-11e4-9ff1-514c4e39b9d0.png)

*** plugin settings
![screen shot 2015-03-10 at 10 18 01 am](https://cloud.githubusercontent.com/assets/3331444/6580562/cc43f156-c70e-11e4-9680-f7d306797012.png)

**Comment by cyphactor** [comment]
I finished completing all of this. Therefore, I am closing this issue.
